services:
  api:
    restart: always
    build: .
    env_file: .env
    command: ["pnpm", "start"]
    ports:
      - 3000:${PORT}
    networks:
      - web

  worker:
    build: .
    env_file:
      - .env
    restart: always
    command: ["pnpm", "start:worker"]
    networks:
      - web

networks:
  web:
    external: true
